#!/bin/bash
declare -a arr=("tmp" "models" "predictions" "cv")

## now loop through the above array
for dir in "${arr[@]}"
do
    if [ ! -d "$dir" ]; then
        echo "$dir not exist, create"
        mkdir $dir
    else
        echo "$dir exists, clean"
        rm -r $dir/*
    fi
done

